#!/bin/bash

PYTHONPATH='.' python plenoxels/main.py --device 0 --config-path plenoxels/configs/final/samsung2024/cutroastedbeef_hybrid.py expname=cut_roasted_beef data_downsample=4 vis_every=300 pose_npy_suffix=align_bd
# PYTHONPATH='.' python plenoxels/main.py --device 0 --config-path plenoxels/configs/final/DyNeRF/dynerf_hybrid.py expname=cook_spinach num_steps=1 data_downsample=4
# PYTHONPATH='.' python plenoxels/main.py --device 0 --config-path plenoxels/configs/final/DyNeRF/dynerf_hybrid.py expname=coffee_martini num_steps=1 data_downsample=4

# PYTHONPATH='.' python plenoxels/main.py --device 0 --config-path plenoxels/configs/final/samsung2024/room1_hybrid.py data_downsample=2 pose_npy_suffix=sparf use_intrinsic=True expname=room1_sparf_bbox1.5 selection=[[1,3,7,9],[5]] bbox_mult=[1.5,1.5,1.5] early_stop=40000
# PYTHONPATH='.' python plenoxels/main.py --device 0 --config-path plenoxels/configs/final/samsung2024/room1_hybrid.py data_downsample=2 pose_npy_suffix=colmap use_intrinsic=True expname=room1_colmap_ndcnear0.4far4.0 selection=[[1,3,7,9],[5]] ndc_near=0.4 ndc_far=4.0 early_stop=40000
# PYTHONPATH='.' python plenoxels/main.py --device 0 --config-path plenoxels/configs/final/samsung2024/room1_hybrid.py data_downsample=2 pose_npy_suffix=colmap use_intrinsic=True expname=room1_colmap_ndcnear0.8far4.0 selection=[[1,3,7,9],[5]] ndc_near=0.8 ndc_far=4.0 early_stop=40000
# PYTHONPATH='.' python plenoxels/main.py --device 0 --config-path plenoxels/configs/final/samsung2024/room1_hybrid.py data_downsample=2 pose_npy_suffix=sparf use_intrinsic=True expname=room1_sparf_ndcnear0.8far4.0 selection=[[1,3,7,9],[5]] ndc_near=0.8 ndc_far=4.0 early_stop=40000
# PYTHONPATH='.' python plenoxels/main.py --device 0 --config-path plenoxels/configs/final/samsung2024/room1_hybrid.py data_downsample=2 pose_npy_suffix=sparf use_intrinsic=True expname=room1_sparf_cam_scale0.25 selection=[[1,3,7,9],[5]] cam_scale=0.25 early_stop=40000
# PYTHONPATH='.' python plenoxels/main.py --device 0 --config-path plenoxels/configs/final/samsung2024/room1_hybrid.py data_downsample=2 pose_npy_suffix=sparf use_intrinsic=True expname=room1_sparf_cam_scale1.5 selection=[[1,3,7,9],[5]] cam_scale=1.5 early_stop=40000